### ISSUE TITLE
Dual Column Nutrition Label Support

### ISSUE THREAD

**Issue by soleo** [nutritionix/vue-nutrition-label#3]
FDA also requires dual column labeling for some products.

Reference
 
- https://www.fsis.usda.gov/wps/wcm/connect/a8674ea1-0c26-4bf3-8413-43b6551c0680/2014-0024.pdf?MOD=AJPERES

- https://www.esha.com/dual-column-nutrition-facts-label/

- https://www.fda.gov/regulatory-information/search-fda-guidance-documents/guidance-industry-food-labeling-serving-sizes-foods-can-reasonably-be-consumed-one-eating-occasion

Any plans to support this?

**Comment by majin22** [comment]
sorry but not at the moment
